/**
 * Turns the validated model into idempotent seed SQL.
 *
 * Every statement upserts on a stable natural key (source id, unit/skill/
 * lesson/concept key, (concept, language)), so re-running the seed after an
 * edit updates rows in place and never duplicates them. Learner progress
 * references ids that therefore survive a rebuild.
 *
 * One rule protects moderation done directly in the database: a translation
 * disabled in SQL stays disabled on rebuild until someone re-enables it there.
 */
import type { Concept, Model, Translation } from "./model.ts";
import { shortHash, sqlString, sqlTextArray } from "./text.ts";

export type Lesson = {
  key: string;
  skill: string;
  position: number;
  title: string;
  type: "learn" | "practice";
  concepts: string[];
};

/** Words per "learn" lesson. Four new words are introduced at a time. */
const WORDS_PER_LESSON = 6;

/**
 * Lessons are derived, not authored: a skill's words and sentences are dealt
 * evenly into short "learn" lessons in file order, followed by one "practice"
 * lesson that recombines the whole skill. Adding content to a skill therefore
 * grows its lessons with no curriculum edit.
 */
export function deriveLessons(model: Model): Lesson[] {
  const lessons: Lesson[] = [];
  for (const unit of model.curriculum.units) {
    for (const skill of unit.skills) {
      const members = [...model.concepts.values()].filter(
        (c) => c.skill === skill.key && c.status !== "disabled",
      );
      const words = members.filter((c) => c.kind !== "sentence");
      const sentences = members.filter((c) => c.kind === "sentence");
      if (members.length < 4) continue;

      const n = Math.max(1, Math.round(words.length / WORDS_PER_LESSON) || Math.ceil(sentences.length / 5));
      const deal = <T,>(items: T[], i: number) =>
        items.slice(Math.floor((i * items.length) / n), Math.floor(((i + 1) * items.length) / n));

      for (let i = 0; i < n; i++) {
        const w = deal(words, i);
        const s = deal(sentences, i);
        const concepts = [...w, ...s].map((c) => c.key);
        if (concepts.length < 4) continue;
        lessons.push({
          key: `${skill.key}-${i + 1}`,
          skill: skill.key,
          position: i + 1,
          title: titleFor(w.length ? w : s),
          type: "learn",
          concepts,
        });
      }
      if (members.length >= 10) {
        lessons.push({
          key: `${skill.key}-practice`,
          skill: skill.key,
          position: n + 1,
          title: "Put it together",
          type: "practice",
          concepts: members.map((c) => c.key),
        });
      }
    }
  }
  return lessons;
}

function titleFor(concepts: Concept[]): string {
  // "Hello, good morning, how are you…": first word capitalised, the rest in
  // running-text case unless they are proper nouns (Monday, Germany).
  const names = concepts.slice(0, 3).map((c, i) => {
    const g = c.gloss.replace(/^to /, "").replace(/\s*\([^)]*\)/g, "").replace(/[.?!]$/, "");
    if (i === 0) return g.charAt(0).toUpperCase() + g.slice(1);
    return c.proper || /^I\b/.test(g) ? g : g.charAt(0).toLowerCase() + g.slice(1);
  });
  const title = names.join(", ") + (concepts.length > 3 ? "…" : "");
  return title.length > 60 ? `${title.slice(0, 57)}…` : title;
}

const HEADER = (name: string, label: string) =>
  `-- ${name}\n-- GENERATED by scripts/content/build-seed.ts from content/ (${label}).\n-- Do not edit by hand: change the files under content/ and rebuild.\n\n`;

function chunk<T>(items: T[], size: number): T[][] {
  const out: T[][] = [];
  for (let i = 0; i < items.length; i += size) out.push(items.slice(i, i + size));
  return out;
}

export function emitSql(model: Model, lessons: Lesson[]): Record<string, string> {
  const files: Record<string, string> = {};
  const label = `build ${shortHash(JSON.stringify([...model.concepts.keys()]) + JSON.stringify([...model.translations.entries()].map(([k, v]) => [k, [...v.values()].map((t) => t.text)])))}`;
  const languages = Object.entries(model.languages);

  // --- sources, languages, courses, batches --------------------------------
  let sql = HEADER("0010_learn_sources.sql", label);
  sql += "insert into content_sources (id, name, source_type, source_url, license, license_url, author, attribution_text, commercial_use_allowed, modification_allowed, share_alike, requires_item_attribution, item_url_template, is_enabled, license_verified_at, notes) values\n";
  sql += model.sources.map((s) => `  (${[
    sqlString(s.id), sqlString(s.name), sqlString(s.source_type), sqlString(s.source_url),
    sqlString(s.license), sqlString(s.license_url), sqlString(s.author), sqlString(s.attribution_text),
    s.commercial_use_allowed, s.modification_allowed, s.share_alike, s.requires_item_attribution,
    sqlString(s.item_url_template), s.is_enabled,
    s.license_verified_at ? `${sqlString(s.license_verified_at)}::date` : "null", sqlString(s.notes),
  ].join(", ")})`).join(",\n");
  sql += `
on conflict (id) do update set
  name = excluded.name, source_type = excluded.source_type, source_url = excluded.source_url,
  license = excluded.license, license_url = excluded.license_url, author = excluded.author,
  attribution_text = excluded.attribution_text,
  commercial_use_allowed = excluded.commercial_use_allowed,
  modification_allowed = excluded.modification_allowed, share_alike = excluded.share_alike,
  requires_item_attribution = excluded.requires_item_attribution,
  item_url_template = excluded.item_url_template, is_enabled = excluded.is_enabled,
  license_verified_at = excluded.license_verified_at, notes = excluded.notes, updated_at = now();\n\n`;

  sql += "-- Languages used by the content (inserted if missing, never renamed here).\n";
  sql += "insert into languages (code, name, native_name, flag_emoji, is_launch_language, speech_locale) values\n";
  sql += languages.map(([code, l]) => `  (${[sqlString(code), sqlString(l.name), sqlString(l.nativeName), sqlString(l.flag), "true", sqlString(l.speechLocale)].join(", ")})`).join(",\n");
  sql += "\non conflict (code) do update set speech_locale = excluded.speech_locale, is_launch_language = true;\n\n";

  sql += "insert into courses (language_code, title, description) values\n";
  sql += model.curriculum.courses.map((c) => `  (${sqlString(c.language)}, ${sqlString(c.title)}, ${sqlString(c.description)})`).join(",\n");
  sql += "\non conflict (language_code) do update set title = excluded.title, description = excluded.description;\n\n";

  // One import batch per source per build, so every row can be traced back to
  // the run that last wrote it.
  const perSource = new Map<string, { concepts: number; translations: Record<string, number> }>();
  for (const c of model.concepts.values()) {
    const s = perSource.get(c.source) ?? { concepts: 0, translations: {} };
    s.concepts++;
    perSource.set(c.source, s);
  }
  for (const byLang of model.translations.values()) {
    for (const t of byLang.values()) {
      const s = perSource.get(t.source) ?? { concepts: 0, translations: {} };
      s.translations[t.lang] = (s.translations[t.lang] ?? 0) + 1;
      perSource.set(t.source, s);
    }
  }
  sql += "insert into content_import_batches (source_id, tool, label, item_count, stats)\nselect v.source_id, 'scripts/content/build-seed.ts', v.label, v.item_count, v.stats::jsonb\nfrom (values\n";
  sql += [...perSource.entries()].map(([src, s]) => {
    const count = s.concepts + Object.values(s.translations).reduce((a, b) => a + b, 0);
    return `  (${sqlString(src)}, ${sqlString(label)}, ${count}, ${sqlString(JSON.stringify(s))})`;
  }).join(",\n");
  sql += "\n) as v(source_id, label, item_count, stats)\nwhere not exists (select 1 from content_import_batches b where b.source_id = v.source_id and b.label = v.label);\n";
  files["0010_learn_sources.sql"] = sql;

  // --- curriculum ----------------------------------------------------------
  sql = HEADER("0011_learn_curriculum.sql", label);
  const units = model.curriculum.units;
  sql += "insert into units (key, cefr_level, position, title, description, language_code, is_active) values\n";
  sql += units.map((u, i) => `  (${[sqlString(u.key), `'${u.cefr}'::cefr_level`, i + 1, sqlString(u.title), sqlString(u.description), sqlString(u.language ?? null), "true"].join(", ")})`).join(",\n");
  sql += "\non conflict (key) do update set cefr_level = excluded.cefr_level, position = excluded.position, title = excluded.title, description = excluded.description, language_code = excluded.language_code, is_active = true;\n\n";
  sql += `update units set is_active = false where key <> all (${sqlTextArray(units.map((u) => u.key))});\n\n`;

  const skillRows = units.flatMap((u) => u.skills.map((s, i) => ({ ...s, unit: u.key, position: i + 1 })));
  sql += "insert into skills (key, unit_id, position, title, description, icon, language_code, is_active)\nselect v.key, u.id, v.position, v.title, v.description, v.icon, v.language_code, true\nfrom (values\n";
  sql += skillRows.map((s) => `  (${[sqlString(s.key), sqlString(s.unit), s.position, sqlString(s.title), sqlString(s.description), sqlString(s.icon), sqlString(s.language ?? null)].join(", ")})`).join(",\n");
  sql += "\n) as v(key, unit_key, position, title, description, icon, language_code)\njoin units u on u.key = v.unit_key\non conflict (key) do update set unit_id = excluded.unit_id, position = excluded.position, title = excluded.title, description = excluded.description, icon = excluded.icon, language_code = excluded.language_code, is_active = true;\n\n";
  sql += `update skills set is_active = false where key <> all (${sqlTextArray(skillRows.map((s) => s.key))});\n`;
  files["0011_learn_curriculum.sql"] = sql;

  // --- concepts ------------------------------------------------------------
  sql = HEADER("0012_learn_concepts.sql", label);
  const concepts = [...model.concepts.values()];
  for (const part of chunk(concepts, 250)) {
    sql += "insert into concepts (key, kind, part_of_speech, cefr_level, topic, skill_id, sense_group, gloss, situation, is_social, status, source_id, import_batch_id)\n";
    sql += "select v.key, v.kind::concept_kind, v.pos, v.cefr::cefr_level, v.topic, s.id, v.sense_group, v.gloss, v.situation, v.is_social, v.status::content_status, v.source_id,\n";
    sql += `  (select max(b.id) from content_import_batches b where b.source_id = v.source_id and b.label = ${sqlString(label)})\nfrom (values\n`;
    sql += part.map((c) => `  (${[
      sqlString(c.key), sqlString(c.kind), sqlString(c.pos), sqlString(c.cefr), sqlString(c.topic),
      sqlString(c.skill), sqlString(c.group), sqlString(c.gloss), sqlString(c.situation),
      c.social, sqlString(c.status), sqlString(c.source),
    ].join(", ")})`).join(",\n");
    sql += "\n) as v(key, kind, pos, cefr, topic, skill_key, sense_group, gloss, situation, is_social, status, source_id)\n";
    sql += "left join skills s on s.key = v.skill_key\n";
    sql += "on conflict (key) do update set kind = excluded.kind, part_of_speech = excluded.part_of_speech, cefr_level = excluded.cefr_level, topic = excluded.topic, skill_id = excluded.skill_id, sense_group = excluded.sense_group, gloss = excluded.gloss, situation = excluded.situation, is_social = excluded.is_social,\n";
    sql += "  status = case when concepts.status = 'disabled' and excluded.status <> 'disabled' then concepts.status else excluded.status end,\n";
    sql += "  source_id = excluded.source_id, import_batch_id = excluded.import_batch_id, updated_at = now();\n\n";
  }
  files["0012_learn_concepts.sql"] = sql;

  // --- translations, one file per language -----------------------------------
  for (const [lang] of languages) {
    const rows: Translation[] = [];
    for (const byLang of model.translations.values()) {
      const t = byLang.get(lang);
      if (t && model.concepts.has(t.key)) rows.push(t);
    }
    sql = HEADER(`0013_learn_translations_${lang}.sql`, label);
    sql += `-- ${rows.length} ${model.languages[lang].name} texts.\n\n`;
    for (const part of chunk(rows, 250)) {
      sql += "insert into concept_translations (concept_id, language_code, text, alternatives, tokens, cloze_index, cloze_pos, gender, note, status, source_id, source_external_id, source_author, license, import_batch_id)\n";
      sql += "select c.id, v.lang, v.text, v.alternatives, v.tokens, v.cloze_index, v.cloze_pos, v.gender, v.note, v.status::content_status, v.source_id, v.ext_id, v.author, v.license,\n";
      sql += `  (select max(b.id) from content_import_batches b where b.source_id = v.source_id and b.label = ${sqlString(label)})\nfrom (values\n`;
      sql += part.map((t) => `  (${[
        sqlString(t.key), sqlString(t.lang), sqlString(t.text), sqlTextArray(t.alternatives),
        sqlTextArray(t.tokens), t.clozeIndex === null ? "null::smallint" : `${t.clozeIndex}::smallint`,
        sqlString(t.clozePos), sqlString(t.gender), sqlString(t.note), sqlString(t.status),
        sqlString(t.source), sqlString(t.externalId), sqlString(t.author), sqlString(t.license),
      ].join(", ")})`).join(",\n");
      sql += "\n) as v(key, lang, text, alternatives, tokens, cloze_index, cloze_pos, gender, note, status, source_id, ext_id, author, license)\n";
      sql += "join concepts c on c.key = v.key\n";
      sql += "on conflict (concept_id, language_code) do update set text = excluded.text, alternatives = excluded.alternatives, tokens = excluded.tokens, cloze_index = excluded.cloze_index, cloze_pos = excluded.cloze_pos, gender = excluded.gender, note = excluded.note,\n";
      sql += "  status = case when concept_translations.status = 'disabled' and excluded.status <> 'disabled' then concept_translations.status else excluded.status end,\n";
      sql += "  source_id = excluded.source_id, source_external_id = excluded.source_external_id, source_author = excluded.source_author, license = excluded.license, import_batch_id = excluded.import_batch_id, updated_at = now();\n\n";
    }
    files[`0013_learn_translations_${lang}.sql`] = sql;
  }

  // --- lessons -------------------------------------------------------------
  sql = HEADER("0014_learn_lessons.sql", label);
  sql += `-- ${lessons.length} lessons derived from ${skillRows.length} skills.\n\n`;
  sql += "insert into lessons (key, skill_id, position, title, lesson_type, is_active)\nselect v.key, s.id, v.position, v.title, v.lesson_type, true\nfrom (values\n";
  sql += lessons.map((l) => `  (${[sqlString(l.key), sqlString(l.skill), l.position, sqlString(l.title), sqlString(l.type)].join(", ")})`).join(",\n");
  sql += "\n) as v(key, skill_key, position, title, lesson_type)\njoin skills s on s.key = v.skill_key\n";
  sql += "on conflict (key) do update set skill_id = excluded.skill_id, position = excluded.position, title = excluded.title, lesson_type = excluded.lesson_type, is_active = true;\n\n";
  sql += `update lessons set is_active = false where key <> all (${sqlTextArray(lessons.map((l) => l.key))});\n\n`;
  sql += `delete from lesson_concepts where lesson_id in (select id from lessons where key = any (${sqlTextArray(lessons.map((l) => l.key))}));\n\n`;
  const links = lessons.flatMap((l) => l.concepts.map((k, i) => [l.key, k, i] as const));
  for (const part of chunk(links, 500)) {
    sql += "insert into lesson_concepts (lesson_id, concept_id, position)\nselect l.id, c.id, v.position\nfrom (values\n";
    sql += part.map(([l, c, i]) => `  (${sqlString(l)}, ${sqlString(c)}, ${i})`).join(",\n");
    sql += "\n) as v(lesson_key, concept_key, position)\njoin lessons l on l.key = v.lesson_key\njoin concepts c on c.key = v.concept_key\non conflict do nothing;\n\n";
  }
  files["0014_learn_lessons.sql"] = sql;

  return files;
}

export function stats(model: Model, lessons: Lesson[]) {
  const perLang: Record<string, { words: number; phrases: number; sentences: number; total: number }> = {};
  for (const [key, byLang] of model.translations) {
    const c = model.concepts.get(key);
    if (!c || c.status === "disabled") continue;
    for (const t of byLang.values()) {
      if (t.status !== "active") continue;
      const s = (perLang[t.lang] ??= { words: 0, phrases: 0, sentences: 0, total: 0 });
      if (c.kind === "word") s.words++;
      else if (c.kind === "phrase") s.phrases++;
      else s.sentences++;
      s.total++;
    }
  }
  const skills = model.curriculum.units.reduce((n, u) => n + u.skills.length, 0);
  return {
    concepts: model.concepts.size,
    units: model.curriculum.units.length,
    skills,
    lessons: lessons.length,
    perLanguage: perLang,
  };
}
