/**
 * npm run content:import:cldr
 *
 * Generates content/concepts/cldr.tsv — weekday, month, country and language
 * names in every course language — from Unicode CLDR as bundled in Node's ICU.
 * No network: Intl already carries the data.
 *
 * Licence: Unicode License v3 (commercial use, modification and
 * redistribution allowed; keep the notice, which the Licenses page shows).
 * The CLDR version is written into the file because names do change between
 * releases (English "Turkey" became "Türkiye").
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const root = join(import.meta.dirname, "../../content");
const languages = Object.keys(JSON.parse(readFileSync(join(root, "languages.json"), "utf8")));

// Grammatical gender of the *category* where every member shares it, so the
// build does not warn about the missing article (German weekdays and months
// are all masculine, Spanish ones too).
const WEEKDAY_GENDER: Record<string, string> = { de: "m", es: "m" };
const LANGUAGE_NAME_GENDER: Record<string, string> = { de: "n", es: "m", nl: "n" };

const WEEKDAYS = ["mon", "tue", "wed", "thu", "fri", "sat", "sun"];
const MONTHS = ["jan", "feb", "mar", "apr", "may", "jun", "jul", "aug", "sep", "oct", "nov", "dec"];
/** Countries a learner in this app is most likely to mention. */
const COUNTRIES = ["DE", "ES", "NL", "TR", "GB", "US", "FR", "IT", "AT", "CH", "BE", "PT", "GR", "PL"];
const LANGUAGES = ["de", "es", "nl", "tr", "en", "fr", "it", "pt", "ar"];

type Row = {
  key: string;
  pos: string;
  cefr: string;
  skill: string;
  topic: string;
  flags: string;
  texts: Record<string, string>;
};

function cell(text: string, gender?: string) {
  return gender ? `${text} {${gender}}` : text;
}

const rows: Row[] = [];

// 2024-01-01 was a Monday.
WEEKDAYS.forEach((key, i) => {
  const date = new Date(Date.UTC(2024, 0, 1 + i, 12));
  const texts: Record<string, string> = {};
  for (const lang of languages) {
    const name = new Intl.DateTimeFormat(lang, { weekday: "long", timeZone: "UTC" }).format(date);
    texts[lang] = cell(name, WEEKDAY_GENDER[lang]);
  }
  rows.push({ key: `day-${key}`, pos: "noun", cefr: "A1", skill: "days", topic: "weekdays", flags: "proper", texts });
});

MONTHS.forEach((key, i) => {
  const date = new Date(Date.UTC(2024, i, 15, 12));
  const texts: Record<string, string> = {};
  for (const lang of languages) {
    // "LLLL" (standalone) is what a month name looks like on its own.
    const name = new Intl.DateTimeFormat(lang, { month: "long", timeZone: "UTC" }).format(date);
    texts[lang] = cell(name, WEEKDAY_GENDER[lang]);
  }
  rows.push({ key: `month-${key}`, pos: "noun", cefr: "A2", skill: "months", topic: "months", flags: "proper", texts });
});

for (const code of COUNTRIES) {
  const texts: Record<string, string> = {};
  for (const lang of languages) {
    texts[lang] = new Intl.DisplayNames([lang], { type: "region" }).of(code) ?? "";
  }
  rows.push({ key: `country-${code.toLowerCase()}`, pos: "noun", cefr: "A1", skill: "countries", topic: "countries", flags: "proper", texts });
}

for (const code of LANGUAGES) {
  const texts: Record<string, string> = {};
  for (const lang of languages) {
    const name = new Intl.DisplayNames([lang], { type: "language" }).of(code) ?? "";
    texts[lang] = cell(name, LANGUAGE_NAME_GENDER[lang]);
  }
  rows.push({ key: `lang-${code}`, pos: "noun", cefr: "A1", skill: "languages", topic: "language-names", flags: "proper", texts });
}

const header = ["key", "kind", "pos", "cefr", "skill", "topic", ...languages, "situation", "flags"];
const out = [
  "# GENERATED by scripts/content/import-cldr.ts — do not edit by hand; re-run the importer.",
  `# Unicode CLDR ${process.versions.cldr ?? "unknown"} via ICU ${process.versions.icu ?? "unknown"} (Node ${process.versions.node}).`,
  "# Licence: Unicode License v3 — https://www.unicode.org/license.txt",
  "#source: unicode-cldr",
  header.join("\t"),
  ...rows.map((r) =>
    [r.key, "w", r.pos, r.cefr, r.skill, r.topic, ...languages.map((l) => r.texts[l] ?? ""), "", r.flags].join("\t"),
  ),
  "",
].join("\n");

writeFileSync(join(root, "concepts", "cldr.tsv"), out);
console.log(`Wrote ${rows.length} CLDR concepts × ${languages.length} languages to content/concepts/cldr.tsv`);
