/**
 * npm run content:import:wikidata -- --dump <latest-lexemes.json>
 *
 * Streams the Wikidata lexeme dump (CC0 1.0) and writes a review report:
 *
 *   content/imported/wikidata/gender-check.tsv   our noun genders that disagree
 *   content/imported/wikidata/suggestions.tsv    candidate translations for
 *                                                concepts missing a language
 *
 * Nothing here edits the curriculum: a human accepts a suggestion by copying
 * it into content/ (use `#source: wikidata-lexemes` and the lexeme id as
 * ext_id when the text comes from Wikidata).
 *
 * Get the dump (weekly, ~450 MB compressed) from
 *   https://dumps.wikimedia.org/wikidatawiki/entities/latest-lexemes.json.bz2
 * and `bunzip2` it. Bulk dumps, not the query service, are Wikimedia's
 * recommended route for anything larger than a lookup.
 */
import { createReadStream, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { createInterface } from "node:readline";
import { loadModel } from "./lib/model.ts";
import { analyse, parseDumpLine, type Lexeme } from "./lib/wikidata.ts";

const args = process.argv.slice(2);
const dumpArg = args.indexOf("--dump");
if (dumpArg < 0) {
  console.error("Usage: npm run content:import:wikidata -- --dump <path to latest-lexemes.json>");
  process.exit(1);
}
const rootArg = args.indexOf("--root");
const root = rootArg >= 0 ? args[rootArg + 1] : join(import.meta.dirname, "../../content");

const lexemes: Lexeme[] = [];
const lines = createInterface({ input: createReadStream(args[dumpArg + 1], "utf8"), crlfDelay: Infinity });
for await (const line of lines) {
  const lexeme = parseDumpLine(line);
  if (lexeme) lexemes.push(lexeme);
}

const model = loadModel(root);
const { genderIssues, suggestions } = analyse(model, lexemes);

const out = join(root, "imported", "wikidata");
mkdirSync(out, { recursive: true });
const note = "# GENERATED by scripts/content/import-wikidata.ts from the Wikidata lexeme dump (CC0 1.0). Review only; not loaded by the build.";
writeFileSync(
  join(out, "gender-check.tsv"),
  [note, "key\tlang\ttext\tours\twikidata\tlexeme", ...genderIssues.map((g) => [g.key, g.lang, g.text, g.ours, g.wikidata, g.lexeme].join("\t"))].join("\n") + "\n",
);
writeFileSync(
  join(out, "suggestions.tsv"),
  [note, "key\tlang\tsuggestion\tlexemes", ...suggestions.map((s) => [s.key, s.lang, s.suggestion, s.lexemes].join("\t"))].join("\n") + "\n",
);

console.log(`Read ${lexemes.length} lexemes in our languages.`);
console.log(`${genderIssues.length} gender disagreements, ${suggestions.length} translation suggestions -> content/imported/wikidata/`);
