-- 0010_learn_sources.sql
-- GENERATED by scripts/content/build-seed.ts from content/ (build 5a6c7cb8).
-- Do not edit by hand: change the files under content/ and rebuild.

insert into content_sources (id, name, source_type, source_url, license, license_url, author, attribution_text, commercial_use_allowed, modification_allowed, share_alike, requires_item_attribution, item_url_template, is_enabled, license_verified_at, notes) values
  ('lingua-match-editorial', 'Lingua Match editorial content', 'editorial', null, 'Proprietary — original work of Lingua Match', null, 'Lingua Match', 'Vocabulary, example sentences and curriculum written for Lingua Match. Not derived from any course or proprietary word list.', true, true, false, false, null, true, null, 'Hand-written and cross-checked in five languages. CEFR levels are an editorial judgement, not an official certification.'),
  ('unicode-cldr', 'Unicode CLDR (via ICU / JavaScript Intl)', 'reference_data', 'https://cldr.unicode.org/', 'Unicode-3.0 (Unicode License v3)', 'https://www.unicode.org/license.txt', 'Unicode, Inc.', 'Day, month, country and language names from the Unicode Common Locale Data Repository (CLDR). Copyright © 1991-2025 Unicode, Inc. Distributed under the Unicode License v3; see https://www.unicode.org/license.txt.', true, true, false, false, null, true, '2026-09-27'::date, 'Generated offline by scripts/content/import-cldr.ts from the ICU data bundled with Node. The CLDR version is recorded in the generated files.'),
  ('tatoeba', 'Tatoeba', 'dataset', 'https://tatoeba.org/', 'CC BY 2.0 FR (some sentences CC0 1.0)', 'https://creativecommons.org/licenses/by/2.0/fr/', 'Tatoeba contributors', 'Example sentences from Tatoeba (https://tatoeba.org), each credited to its contributor, licensed CC BY 2.0 FR unless marked CC0 1.0. Sentences may have been lightly normalised (spacing, punctuation).', true, true, false, true, 'https://tatoeba.org/en/sentences/show/{id}', true, '2026-09-27'::date, 'Text only. Tatoeba audio is licensed per speaker (some non-commercial) and is never imported. Imported sentences start as needs_review.'),
  ('wikidata-lexemes', 'Wikidata Lexemes', 'dataset', 'https://www.wikidata.org/wiki/Wikidata:Lexicographical_data', 'CC0 1.0', 'https://creativecommons.org/publicdomain/zero/1.0/', 'Wikidata contributors', 'Lexical data (lemmas, grammatical gender, cross-language sense links) from Wikidata, dedicated to the public domain under CC0 1.0.', true, true, false, false, 'https://www.wikidata.org/wiki/Lexeme:{id}', true, '2026-09-27'::date, 'Used through scripts/content/import-wikidata.ts to check noun genders and suggest missing translations for review. Glosses and usage examples are never copied.')
on conflict (id) do update set
  name = excluded.name, source_type = excluded.source_type, source_url = excluded.source_url,
  license = excluded.license, license_url = excluded.license_url, author = excluded.author,
  attribution_text = excluded.attribution_text,
  commercial_use_allowed = excluded.commercial_use_allowed,
  modification_allowed = excluded.modification_allowed, share_alike = excluded.share_alike,
  requires_item_attribution = excluded.requires_item_attribution,
  item_url_template = excluded.item_url_template, is_enabled = excluded.is_enabled,
  license_verified_at = excluded.license_verified_at, notes = excluded.notes, updated_at = now();

-- Languages used by the content (inserted if missing, never renamed here).
insert into languages (code, name, native_name, flag_emoji, is_launch_language, speech_locale) values
  ('en', 'English', 'English', '🇬🇧', true, 'en-GB'),
  ('de', 'German', 'Deutsch', '🇩🇪', true, 'de-DE'),
  ('es', 'Spanish', 'Español', '🇪🇸', true, 'es-ES'),
  ('nl', 'Dutch', 'Nederlands', '🇳🇱', true, 'nl-NL'),
  ('tr', 'Turkish', 'Türkçe', '🇹🇷', true, 'tr-TR')
on conflict (code) do update set speech_locale = excluded.speech_locale, is_launch_language = true;

insert into courses (language_code, title, description) values
  ('de', 'German', 'Everyday German from your first hello to making plans with a match.'),
  ('es', 'Spanish', 'Everyday Spanish from your first hello to making plans with a match.'),
  ('nl', 'Dutch', 'Everyday Dutch from your first hello to making plans with a match.'),
  ('tr', 'Turkish', 'Everyday Turkish from your first hello to making plans with a match.'),
  ('en', 'English', 'Everyday English from your first hello to making plans with a match.')
on conflict (language_code) do update set title = excluded.title, description = excluded.description;

insert into content_import_batches (source_id, tool, label, item_count, stats)
select v.source_id, 'scripts/content/build-seed.ts', v.label, v.item_count, v.stats::jsonb
from (values
  ('lingua-match-editorial', 'build 5a6c7cb8', 2130, '{"concepts":355,"translations":{"en":355,"de":355,"es":355,"nl":355,"tr":355}}'),
  ('unicode-cldr', 'build 5a6c7cb8', 252, '{"concepts":42,"translations":{"en":42,"de":42,"es":42,"nl":42,"tr":42}}')
) as v(source_id, label, item_count, stats)
where not exists (select 1 from content_import_batches b where b.source_id = v.source_id and b.label = v.label);
