-- 0011_learn_curriculum.sql
-- GENERATED by scripts/content/build-seed.ts from content/ (build 5a6c7cb8).
-- Do not edit by hand: change the files under content/ and rebuild.

insert into units (key, cefr_level, position, title, description, language_code, is_active) values
  ('a1-first-steps', 'A1'::cefr_level, 1, 'First steps', 'Say hello, introduce yourself and be polite.', null, true),
  ('a1-where-from', 'A1'::cefr_level, 2, 'Where you''re from', 'Countries, languages and numbers.', null, true),
  ('a1-about-me', 'A1'::cefr_level, 3, 'About me', 'Age, work, study and the people close to you.', null, true),
  ('a1-people', 'A1'::cefr_level, 4, 'People', 'Friends, looks and personality.', null, true),
  ('a1-everyday', 'A1'::cefr_level, 5, 'Everyday life', 'Days, time and your daily routine.', null, true),
  ('a1-food-drink', 'A1'::cefr_level, 6, 'Food and drink', 'Order, eat and say what you like.', null, true),
  ('a1-around-town', 'A1'::cefr_level, 7, 'Around town', 'Places, getting around and shopping.', null, true),
  ('a1-free-time', 'A1'::cefr_level, 8, 'Free time', 'Hobbies, music, sport and weekends.', null, true),
  ('a1-home', 'A1'::cefr_level, 9, 'At home', 'Your home, things around you and colours.', null, true),
  ('a2-time-weather', 'A2'::cefr_level, 10, 'Time and weather', 'Months, seasons, weather and making plans.', null, true),
  ('a2-travel', 'A2'::cefr_level, 11, 'Travel', 'Holidays, hotels and getting there.', null, true),
  ('a2-health-feelings', 'A2'::cefr_level, 12, 'Health and feelings', 'Your body, feeling ill and emotions.', null, true),
  ('a2-past', 'A2'::cefr_level, 13, 'Talking about the past', 'Yesterday, last weekend and your story.', null, true),
  ('a2-getting-to-know', 'A2'::cefr_level, 14, 'Getting to know someone', 'Meeting up, opinions and keeping a conversation going.', null, true)
on conflict (key) do update set cefr_level = excluded.cefr_level, position = excluded.position, title = excluded.title, description = excluded.description, language_code = excluded.language_code, is_active = true;

update units set is_active = false where key <> all (array['a1-first-steps', 'a1-where-from', 'a1-about-me', 'a1-people', 'a1-everyday', 'a1-food-drink', 'a1-around-town', 'a1-free-time', 'a1-home', 'a2-time-weather', 'a2-travel', 'a2-health-feelings', 'a2-past', 'a2-getting-to-know']::text[]);

insert into skills (key, unit_id, position, title, description, icon, language_code, is_active)
select v.key, u.id, v.position, v.title, v.description, v.icon, v.language_code, true
from (values
  ('greetings', 'a1-first-steps', 1, 'Greetings', 'Hello, goodbye and how are you.', '👋', null),
  ('introductions', 'a1-first-steps', 2, 'Introductions', 'Your name and nice to meet you.', '🤝', null),
  ('courtesy', 'a1-first-steps', 3, 'Please and thank you', 'Being polite, saying sorry, yes and no.', '🙏', null),
  ('countries', 'a1-where-from', 1, 'Countries', 'Where you come from and where you live.', '🌍', null),
  ('languages', 'a1-where-from', 2, 'Languages', 'What you speak and what you are learning.', '🗣️', null),
  ('numbers', 'a1-where-from', 3, 'Numbers', 'Counting from zero to a hundred.', '🔢', null),
  ('age-birthday', 'a1-about-me', 1, 'Age and birthdays', 'How old you are and when you were born.', '🎂', null),
  ('jobs', 'a1-about-me', 2, 'Work and study', 'Jobs, studies and where you work.', '💼', null),
  ('family', 'a1-about-me', 3, 'Family', 'Parents, siblings and relatives.', '👪', null),
  ('friends', 'a1-people', 1, 'Friends and partners', 'Friends, partners and people you meet.', '🫶', null),
  ('appearance', 'a1-people', 2, 'Appearance', 'Describing how people look.', '🧑', null),
  ('personality', 'a1-people', 3, 'Personality', 'Kind, funny, shy and more.', '✨', null),
  ('days', 'a1-everyday', 1, 'Days of the week', 'Monday to Sunday, today and tomorrow.', '📅', null),
  ('time', 'a1-everyday', 2, 'Telling the time', 'Hours, minutes and times of day.', '⏰', null),
  ('routine', 'a1-everyday', 3, 'Daily routine', 'Waking up, working, sleeping.', '🌅', null),
  ('basic-verbs', 'a1-everyday', 4, 'Basic verbs', 'Have, go, make, want and friends.', '⚙️', null),
  ('drinks', 'a1-food-drink', 1, 'Drinks', 'Coffee, tea, water and more.', '☕', null),
  ('food', 'a1-food-drink', 2, 'Food', 'Everyday food and meals.', '🍞', null),
  ('cafe', 'a1-food-drink', 3, 'At the café', 'Ordering and paying.', '🧾', null),
  ('likes', 'a1-food-drink', 4, 'Likes and dislikes', 'What you love and what you don''t.', '❤️', null),
  ('places', 'a1-around-town', 1, 'Places in town', 'Station, supermarket, park.', '🏙️', null),
  ('transport', 'a1-around-town', 2, 'Getting around', 'Bus, train, bike and car.', '🚲', null),
  ('directions', 'a1-around-town', 3, 'Directions', 'Left, right, straight on.', '🧭', null),
  ('shopping', 'a1-around-town', 4, 'Shopping', 'Prices, sizes and paying.', '🛍️', null),
  ('hobbies', 'a1-free-time', 1, 'Hobbies', 'Reading, cooking, travelling.', '🎨', null),
  ('music', 'a1-free-time', 2, 'Music and films', 'What you listen to and watch.', '🎵', null),
  ('sport', 'a1-free-time', 3, 'Sport', 'Playing, watching and staying fit.', '⚽', null),
  ('weekend', 'a1-free-time', 4, 'The weekend', 'Plans, invitations and free time.', '🎉', null),
  ('home', 'a1-home', 1, 'Home and rooms', 'Flat, kitchen, bedroom.', '🏠', null),
  ('things', 'a1-home', 2, 'Everyday things', 'Phone, keys, bag and more.', '🔑', null),
  ('colours', 'a1-home', 3, 'Colours', 'Red, blue, green and friends.', '🎨', null),
  ('months', 'a2-time-weather', 1, 'Months', 'January to December.', '🗓️', null),
  ('weather', 'a2-time-weather', 2, 'Weather and seasons', 'Sun, rain, summer and winter.', '🌦️', null),
  ('plans', 'a2-time-weather', 3, 'Making plans', 'Next week, later and appointments.', '📌', null),
  ('holidays', 'a2-travel', 1, 'Holidays', 'Beach, mountains and sightseeing.', '🏖️', null),
  ('hotel', 'a2-travel', 2, 'At the hotel', 'Rooms, bookings and keys.', '🛎️', null),
  ('journey', 'a2-travel', 3, 'The journey', 'Tickets, platforms and delays.', '✈️', null),
  ('body', 'a2-health-feelings', 1, 'Body and health', 'Head, stomach and the doctor.', '🩺', null),
  ('feelings', 'a2-health-feelings', 2, 'Feelings', 'Happy, tired, nervous, excited.', '😊', null),
  ('yesterday', 'a2-past', 1, 'Yesterday', 'What you did and where you went.', '⏪', null),
  ('life-story', 'a2-past', 2, 'Your story', 'Where you grew up and what changed.', '📖', null),
  ('meeting-up', 'a2-getting-to-know', 1, 'Meeting up', 'Suggesting a time and place.', '☕', null),
  ('opinions', 'a2-getting-to-know', 2, 'Opinions', 'I think, I agree, in my opinion.', '💬', null),
  ('chatting', 'a2-getting-to-know', 3, 'Keeping the chat going', 'Questions that start real conversations.', '📱', null)
) as v(key, unit_key, position, title, description, icon, language_code)
join units u on u.key = v.unit_key
on conflict (key) do update set unit_id = excluded.unit_id, position = excluded.position, title = excluded.title, description = excluded.description, icon = excluded.icon, language_code = excluded.language_code, is_active = true;

update skills set is_active = false where key <> all (array['greetings', 'introductions', 'courtesy', 'countries', 'languages', 'numbers', 'age-birthday', 'jobs', 'family', 'friends', 'appearance', 'personality', 'days', 'time', 'routine', 'basic-verbs', 'drinks', 'food', 'cafe', 'likes', 'places', 'transport', 'directions', 'shopping', 'hobbies', 'music', 'sport', 'weekend', 'home', 'things', 'colours', 'months', 'weather', 'plans', 'holidays', 'hotel', 'journey', 'body', 'feelings', 'yesterday', 'life-story', 'meeting-up', 'opinions', 'chatting']::text[]);
