-- 999998_practice_runs.sql
-- Daily and Quick challenges built from the new course content (issue #28): a
-- practice run is a deck of five cards generated by the same engine as lessons
-- (learn_compose / learn_build_exercise), graded by learn_grade, feeding the same
-- spaced-repetition table, and paying XP once, at the end.
--
-- Nothing is copied from the lesson code: this file only chooses concepts and a
-- plan, then calls the existing generators and graders. Missions and partner
-- challenges (game_templates / game_sessions) are not touched.
--
-- XP uses the existing 'game_session_completed' reason: a new enum value cannot
-- be added and used by the same migration, and the ledger distinguishes nothing
-- by it today.

-- All the numbers, in one place.
create or replace function public.practice_rules()
returns jsonb
language sql
immutable
as $$
  select jsonb_build_object(
    'cards', 5,
    'min_correct', 3,        -- first-try correct answers needed for any XP
    'daily_first_xp', 15,    -- first rewarded daily run of the day
    'daily_repeat_xp', 5,    -- later rewarded daily runs the same day
    'quick_xp', 10,
    'perfect_bonus', 5       -- every card right on the first try
  );
$$;

create table public.practice_runs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles (id) on delete cascade,
  kind text not null check (kind in ('daily', 'quick')),
  style text check (style in ('meaning', 'build', 'type', 'listen', 'mixed')),
  language_code text not null references public.languages (code),
  known_language_code text not null references public.languages (code),
  -- UTC day, like the rest of the Play hub (see get_play_overview).
  run_date date not null default ((now() at time zone 'utc')::date),
  -- Holds the answer keys, so like lesson_sessions there is NO client read
  -- policy: the browser only ever sees what practice_run_payload() strips.
  exercises jsonb not null,
  results jsonb not null default '{}',
  status text not null default 'in_progress'
    check (status in ('in_progress', 'completed', 'abandoned')),
  correct_count smallint,
  xp_awarded smallint not null default 0,
  created_at timestamptz not null default now(),
  completed_at timestamptz
);

create index practice_runs_user_idx on public.practice_runs (user_id, kind, run_date, status);

alter table public.practice_runs enable row level security;
revoke all on public.practice_runs from public, anon, authenticated;

-- ---------------------------------------------------------------------------
-- Choosing cards
-- ---------------------------------------------------------------------------

-- Picks up to eight concepts (a couple due for review, a couple already met,
-- the rest new and at the learner's level), then lets learn_compose turn them
-- into five exercises. Daily seeds everything from user + date, so two users
-- differ and one user's first daily of the day is reproducible; quick is random.
-- (start_practice_run replays the first daily deck for repeats the same day.)
create or replace function public.practice_build_cards(
  p_uid uuid,
  p_kind text,
  p_style text,
  p_audio boolean,
  p_target text,
  p_known text,
  p_seed text
)
returns jsonb
language plpgsql
volatile
security definer
set search_path = public
as $$
declare
  v_level cefr_level;
  v_picked bigint[];
  v_words bigint[];
  v_sentences bigint[];
  v_plan text[];
  v_cards jsonb;
  v_n int := (public.practice_rules() ->> 'cards')::int;
begin
  select cefr_level into v_level
  from user_languages
  where user_id = p_uid and role = 'learning' and language_code = p_target
  limit 1;
  v_level := coalesce(v_level, 'A1');

  with cand as (
    select c.id, c.kind, c.cefr_level,
           case when p.concept_id is null then 'new'
                when p.next_review_at <= now() then 'due'
                else 'met' end as bucket,
           case when p_kind = 'daily'
                then md5(p_seed || ':' || c.id::text)
                else md5(random()::text || c.id::text) end as sort_key
    from concepts c
    join concept_translations tt
      on tt.concept_id = c.id and tt.language_code = p_target and tt.status = 'active'
    join concept_translations kt
      on kt.concept_id = c.id and kt.language_code = p_known and kt.status = 'active'
    left join user_concept_progress p
      on p.user_id = p_uid and p.language_code = p_target and p.concept_id = c.id
    where c.status = 'active'
  ),
  ranked as (
    select *, row_number() over (partition by bucket order by sort_key) as rn
    from cand
  )
  select array_agg(id order by prio, sort_key)
  into v_picked
  from (
    select id, sort_key,
           case
             when bucket = 'due' and rn <= 2 then 0
             when bucket = 'met' and rn <= 2 then 1
             when bucket = 'new' and cefr_level <= v_level then 2
             when bucket = 'due' then 3
             when bucket = 'met' then 4
             else 5
           end as prio
    from ranked
    order by prio, sort_key
    limit 8
  ) t;

  if coalesce(cardinality(v_picked), 0) = 0 then
    return '[]'::jsonb;
  end if;

  select
    array_agg(c.id) filter (where c.kind in ('word', 'phrase')),
    array_agg(c.id) filter (where c.kind = 'sentence'
                              or (c.kind = 'phrase' and cardinality(tt.tokens) >= 3))
  into v_words, v_sentences
  from concepts c
  join concept_translations tt
    on tt.concept_id = c.id and tt.language_code = p_target and tt.status = 'active'
  where c.id = any (v_picked);

  v_words := coalesce(v_words, '{}');
  v_sentences := coalesce(v_sentences, '{}');

  -- More slots than cards: a slot the content cannot fill is skipped.
  v_plan := case coalesce(p_style, 'mixed')
    when 'meaning' then array['vocab_choice', 'sentence_choice', 'vocab_choice', 'true_false', 'sentence_choice', 'vocab_choice', 'context_choice']
    when 'build'   then array['word_order', 'word_bank', 'word_order', 'word_bank', 'word_order', 'missing_word', 'word_bank']
    when 'type'    then array['type_translation', 'vocab_recall', 'type_translation', 'vocab_recall', 'type_translation', 'vocab_recall', 'type_translation']
    when 'listen'  then array['listen_choice', 'listen_type', 'listen_choice', 'listen_type', 'listen_choice', 'listen_type', 'listen_choice']
    else array['sentence_choice', 'vocab_choice', 'missing_word', 'type_translation', 'word_order', 'vocab_recall', 'true_false']
  end;

  -- The generators draw on random(); seeding it makes the daily run identical
  -- for the whole day. Afterwards the generator is re-seeded from the clock so
  -- later random() calls in this session are not stuck on the daily sequence.
  if p_kind = 'daily' then
    perform setseed(
      ((('x' || substr(md5(p_seed), 1, 7))::bit(28)::int)::float8 / 268435456.0) * 2 - 1);
  end if;

  v_cards := public.learn_compose(v_plan, v_words, v_sentences, p_target, p_known, p_audio, v_words);

  if p_kind = 'daily' then
    perform setseed(
      ((extract(microseconds from clock_timestamp())::numeric % 1000000) / 500000.0 - 1)::float8);
  end if;

  select coalesce(jsonb_agg(e.ex order by e.i), '[]'::jsonb)
  into v_cards
  from jsonb_array_elements(v_cards) with ordinality e(ex, i)
  where e.i <= v_n;

  return v_cards;
end;
$$;

-- What the browser gets for a run: stripped cards plus the answers already given.
create or replace function public.practice_run_payload(p_run_id uuid)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'available', true,
    'run_id', r.id,
    'kind', r.kind,
    'style', r.style,
    'status', r.status,
    'total', jsonb_array_length(r.exercises),
    'target', jsonb_build_object('code', tl.code, 'name', tl.name,
      'flag_emoji', tl.flag_emoji, 'speech_locale', tl.speech_locale),
    'known', jsonb_build_object('code', kl.code, 'name', kl.name,
      'flag_emoji', kl.flag_emoji, 'speech_locale', kl.speech_locale),
    'exercises', public.learn_strip_exercises(r.exercises),
    -- Answers already given, so a refresh resumes at the right card.
    'results', r.results
  )
  from practice_runs r
  join languages tl on tl.code = r.language_code
  join languages kl on kl.code = r.known_language_code
  where r.id = p_run_id;
$$;

-- ---------------------------------------------------------------------------
-- Client API
-- ---------------------------------------------------------------------------

-- p_kind 'daily' (same cards all day, resumes today's unfinished run) or
-- 'quick' (random each call; p_exercise_type picks a style: meaning, build,
-- type, listen). Returns {available:false, reason} when there is nothing to
-- build yet instead of raising.
create or replace function public.start_practice_run(
  p_kind text,
  p_exercise_type text default null,
  p_audio boolean default true
)
returns jsonb
language plpgsql
volatile
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_dir record;
  v_style text;
  v_today date := (now() at time zone 'utc')::date;
  v_cards jsonb;
  v_run_id uuid;
  v_min_cards int := 3;
begin
  if v_uid is null then
    raise exception 'Not authenticated' using errcode = '28000';
  end if;
  if p_kind not in ('daily', 'quick') then
    raise exception 'Unknown practice kind' using errcode = 'check_violation';
  end if;
  if p_kind = 'quick' and p_exercise_type is not null
     and p_exercise_type not in ('meaning', 'build', 'type', 'listen', 'mixed') then
    raise exception 'Unknown exercise type' using errcode = 'check_violation';
  end if;
  v_style := case when p_kind = 'quick' then coalesce(p_exercise_type, 'mixed') else null end;

  begin
    select * into v_dir from public.learn_directions(v_uid);
  exception when check_violation then
    return jsonb_build_object('available', false, 'reason', 'no_course');
  end;

  if p_kind = 'daily' then
    -- Today's unfinished run is simply continued.
    select id into v_run_id from practice_runs
    where user_id = v_uid and kind = 'daily' and run_date = v_today and status = 'in_progress'
    order by created_at desc limit 1;
    if v_run_id is not null then
      return public.practice_run_payload(v_run_id);
    end if;
  else
    update practice_runs set status = 'abandoned'
    where user_id = v_uid and kind = 'quick' and status = 'in_progress';
  end if;

  v_cards := null;
  if p_kind = 'daily' then
    -- The day's deck is fixed by its first run. Picking again later would give
    -- a different deck, because answering moves concepts between "new", "met"
    -- and "due"; repeats therefore replay the stored cards.
    select exercises into v_cards from practice_runs
    where user_id = v_uid and kind = 'daily' and run_date = v_today
      and language_code = v_dir.target and known_language_code = v_dir.known
    order by created_at limit 1;
  end if;

  if v_cards is null then
    v_cards := public.practice_build_cards(
      v_uid, p_kind, v_style, p_audio, v_dir.target, v_dir.known,
      v_uid::text || ':' || v_today::text);
  end if;

  if jsonb_array_length(v_cards) < v_min_cards then
    return jsonb_build_object('available', false, 'reason', 'not_enough_content');
  end if;

  delete from practice_runs
  where user_id = v_uid and status = 'abandoned' and created_at < now() - interval '7 days';

  insert into practice_runs (user_id, kind, style, language_code, known_language_code, run_date, exercises)
  values (v_uid, p_kind, v_style, v_dir.target, v_dir.known, v_today, v_cards)
  returning id into v_run_id;

  return public.practice_run_payload(v_run_id);
end;
$$;

-- Reopening a run (refresh, deep link): the same stripped payload.
create or replace function public.get_practice_run(p_run_id uuid)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
begin
  if v_uid is null then
    raise exception 'Not authenticated' using errcode = '28000';
  end if;
  if not exists (select 1 from practice_runs where id = p_run_id and user_id = v_uid) then
    return null;
  end if;
  return public.practice_run_payload(p_run_id);
end;
$$;

-- The client submits what the learner did, never whether it was right.
-- Idempotent per card: answering twice returns the first verdict.
create or replace function public.answer_practice_card(
  p_run_id uuid,
  p_card_index int,
  p_answer jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
volatile
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_r practice_runs%rowtype;
  v_ex jsonb;
  v_grade jsonb;
  v_result jsonb;
  v_pc record;
begin
  if v_uid is null then
    raise exception 'Not authenticated' using errcode = '28000';
  end if;

  select * into v_r from practice_runs where id = p_run_id for update;
  if v_r.id is null or v_r.user_id <> v_uid then
    raise exception 'Run not found' using errcode = '42501';
  end if;
  if v_r.status <> 'in_progress' then
    raise exception 'This run is already over' using errcode = 'check_violation';
  end if;

  -- Bounds first: jsonb `-> -1` counts from the end and would expose a key.
  if p_card_index is null or p_card_index < 0 or p_card_index >= jsonb_array_length(v_r.exercises) then
    raise exception 'No such card' using errcode = 'check_violation';
  end if;
  v_ex := v_r.exercises -> p_card_index;

  if v_r.results ? p_card_index::text then
    return v_r.results -> p_card_index::text;
  end if;

  if v_ex ->> 'type' in ('listen_choice', 'listen_type') and coalesce((p_answer ->> 'skip')::boolean, false) then
    -- "Can't listen now": shown the answer, not scored, SRS untouched.
    v_result := jsonb_build_object('correct', null, 'note', 'skipped',
      'solution', v_ex ->> 'solution', 'expected', v_ex -> 'answer', 'graded', false);
  else
    v_grade := public.learn_grade(v_ex, p_answer);

    for v_pc in select key::bigint as concept_id, value::boolean as ok
                from jsonb_each_text(v_grade -> 'per_concept') loop
      perform public.learn_record_result(v_uid, v_r.language_code, v_pc.concept_id, v_pc.ok);
    end loop;

    v_result := jsonb_build_object(
      'correct', (v_grade ->> 'correct')::boolean,
      'note', v_grade ->> 'note',
      'solution', v_ex ->> 'solution',
      'expected', v_ex -> 'answer',
      'graded', true);
  end if;

  update practice_runs
  set results = results || jsonb_build_object(p_card_index::text, v_result)
  where id = p_run_id;

  return v_result;
end;
$$;

-- XP happens here, once, at the end of the run:
--   needs min_correct first-try answers; daily 15 (first rewarded run of the
--   day) or 5 (repeats), quick 10; +5 when every card was right.
create or replace function public.finish_practice_run(p_run_id uuid)
returns jsonb
language plpgsql
volatile
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_r practice_runs%rowtype;
  v_rules jsonb := public.practice_rules();
  v_total int;
  v_graded int := 0;
  v_correct int := 0;
  v_xp smallint := 0;
  v_first_daily boolean := false;
  v_perfect boolean;
  v_streak smallint;
  e record;
begin
  if v_uid is null then
    raise exception 'Not authenticated' using errcode = '28000';
  end if;

  select * into v_r from practice_runs where id = p_run_id for update;
  if v_r.id is null or v_r.user_id <> v_uid then
    raise exception 'Run not found' using errcode = '42501';
  end if;
  v_total := jsonb_array_length(v_r.exercises);

  if v_r.status = 'completed' then
    return jsonb_build_object('already_completed', true, 'xp_awarded', v_r.xp_awarded,
      'correct', v_r.correct_count, 'total', v_total, 'kind', v_r.kind);
  end if;
  if v_r.status <> 'in_progress' then
    raise exception 'This run was abandoned' using errcode = 'check_violation';
  end if;

  for e in select (idx - 1)::int as i from jsonb_array_elements(v_r.exercises) with ordinality t(ex, idx) loop
    if not (v_r.results ? e.i::text) then
      raise exception 'Answer every card first' using errcode = 'check_violation';
    end if;
    if (v_r.results -> e.i::text ->> 'graded')::boolean is false then
      continue;
    end if;
    v_graded := v_graded + 1;
    if (v_r.results -> e.i::text ->> 'correct')::boolean then
      v_correct := v_correct + 1;
    end if;
  end loop;

  v_perfect := v_graded = v_total and v_correct = v_total;

  if v_correct >= (v_rules ->> 'min_correct')::int then
    if v_r.kind = 'daily' then
      v_first_daily := not exists (
        select 1 from practice_runs
        where user_id = v_uid and kind = 'daily' and run_date = v_r.run_date
          and status = 'completed' and xp_awarded > 0 and id <> v_r.id);
      v_xp := (case when v_first_daily then (v_rules ->> 'daily_first_xp')::int
                    else (v_rules ->> 'daily_repeat_xp')::int end);
    else
      v_xp := (v_rules ->> 'quick_xp')::int;
    end if;
    if v_perfect then
      v_xp := v_xp + (v_rules ->> 'perfect_bonus')::int;
    end if;
  end if;

  update practice_runs
  set status = 'completed', completed_at = now(), correct_count = v_correct, xp_awarded = v_xp
  where id = p_run_id;

  -- grant_xp ignores zero, so a run below the bar leaves the ledger alone.
  perform public.grant_xp(v_uid, v_xp, 'game_session_completed', 'practice_runs', p_run_id::text);

  select current_streak_days into v_streak from user_progress where user_id = v_uid;

  return jsonb_build_object(
    'already_completed', false,
    'kind', v_r.kind,
    'xp_awarded', v_xp,
    'correct', v_correct,
    'graded', v_graded,
    'total', v_total,
    'perfect', v_perfect,
    'first_daily_today', v_first_daily,
    'streak_days', coalesce(v_streak, 0),
    'review_due', (
      select count(*) from user_concept_progress
      where user_id = v_uid and language_code = v_r.language_code and next_review_at <= now())
  );
end;
$$;

revoke execute on function public.practice_rules() from public, anon;
revoke execute on function public.practice_build_cards(uuid, text, text, boolean, text, text, text) from public, anon, authenticated;
revoke execute on function public.practice_run_payload(uuid) from public, anon, authenticated;
revoke execute on function public.start_practice_run(text, text, boolean) from public, anon;
revoke execute on function public.get_practice_run(uuid) from public, anon;
revoke execute on function public.answer_practice_card(uuid, int, jsonb) from public, anon;
revoke execute on function public.finish_practice_run(uuid) from public, anon;
grant execute on function public.practice_rules() to authenticated;
grant execute on function public.start_practice_run(text, text, boolean) to authenticated;
grant execute on function public.get_practice_run(uuid) to authenticated;
grant execute on function public.answer_practice_card(uuid, int, jsonb) to authenticated;
grant execute on function public.finish_practice_run(uuid) to authenticated;

-- get_play_overview: daily_challenge and practice come from the practice-run engine.
-- It also keeps the effective streak from 999990_streak_timezone.sql (this
-- migration runs after it and replaces the function, so it must include it).
create or replace function public.get_play_overview()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_learning text;
  v_progress jsonb;
  v_daily jsonb;
  v_missions jsonb;
  v_practice jsonb;
  v_available boolean;
  v_done boolean;
  v_rules jsonb := public.practice_rules();
begin
  if v_uid is null then
    raise exception 'Not authenticated' using errcode = '28000';
  end if;

  select language_code into v_learning
  from user_languages where user_id = v_uid and role = 'learning' limit 1;

  select jsonb_build_object(
    'total_xp', total_xp,
    'level', level,
    'league', league,
    'current_streak_days', public.effective_streak_days(v_uid),
    'longest_streak_days', longest_streak_days,
    'last_activity_date', last_activity_date,
    'xp_into_level', total_xp % 100,
    'xp_for_next_level', 100
  )
  into v_progress
  from user_progress where user_id = v_uid;

  -- Daily and quick challenges now come from the practice-run engine
  -- (start_practice_run). Keys stay compatible with the old shape; game_template_id
  -- is null because there is no template behind them any more.
  v_available := exists (select 1 from courses where language_code = v_learning and is_published);

  if v_available then
    v_done := exists (
      select 1 from practice_runs
      where user_id = v_uid and kind = 'daily' and status = 'completed'
        and run_date = (now() at time zone 'utc')::date);
    v_daily := jsonb_build_object(
      'kind', 'daily',
      'key', 'daily',
      'type', 'practice_run',
      'game_template_id', null,
      'title', 'Daily challenge',
      'description', 'Five cards picked for you, the same all day.',
      'xp_reward', case when v_done then (v_rules ->> 'daily_repeat_xp')::int
                        else (v_rules ->> 'daily_first_xp')::int end,
      'completed_today', v_done);
  end if;

  select coalesce(jsonb_agg(jsonb_build_object(
    'match_mission_id', mm.id,
    'match_id', m.id,
    'partner_first_name', partner.first_name,
    'partner_photo_path', partner.primary_photo_path,
    'title', mi.title,
    'description', mi.description,
    'steps_completed', mm.steps_completed,
    'target_steps', mi.target_steps,
    'xp_reward_per_step', mi.xp_reward_per_step,
    'game_template_id', mi.related_game_template_id
  ) order by mm.assigned_at desc), '[]'::jsonb)
  into v_missions
  from match_missions mm
  join matches m on m.id = mm.match_id
  join missions mi on mi.id = mm.mission_id
  join profiles partner
    on partner.id = case when m.user_a = v_uid then m.user_b else m.user_a end
  where mm.status = 'active'
    and m.status = 'active'
    and v_uid in (m.user_a, m.user_b);

  if v_available then
    v_practice := jsonb_build_array(
      jsonb_build_object('kind', 'quick', 'style', 'meaning', 'key', 'quick-meaning', 'type', 'practice_run',
        'game_template_id', null, 'title', 'What does it mean?', 'description', 'Pick the right meaning.',
        'xp_reward', (v_rules ->> 'quick_xp')::int),
      jsonb_build_object('kind', 'quick', 'style', 'build', 'key', 'quick-build', 'type', 'practice_run',
        'game_template_id', null, 'title', 'Build the sentence', 'description', 'Put the words in order.',
        'xp_reward', (v_rules ->> 'quick_xp')::int),
      jsonb_build_object('kind', 'quick', 'style', 'type', 'key', 'quick-type', 'type', 'practice_run',
        'game_template_id', null, 'title', 'Type it', 'description', 'Write the translation.',
        'xp_reward', (v_rules ->> 'quick_xp')::int));
  else
    v_practice := '[]'::jsonb;
  end if;

  return jsonb_build_object(
    'progress', v_progress,
    'daily_challenge', v_daily,
    'match_missions', v_missions,
    'practice', v_practice,
    'learning_language', v_learning
  );
end;
$$;


